// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyRdtpnuPoDLOtydfHk_D5src4bR4MmK0',
    appId: '1:846756640287:web:219ce0d1d6200686cf872a',
    messagingSenderId: '846756640287',
    projectId: 'evahak-6384c',
    authDomain: 'evahak-6384c.firebaseapp.com',
    storageBucket: 'evahak-6384c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEJdfN9VtgS33wdqrOZ4Mg8Zz5Lm2sqc4',
    appId: '1:846756640287:android:bd2ff31a45b970eacf872a',
    messagingSenderId: '846756640287',
    projectId: 'evahak-6384c',
    storageBucket: 'evahak-6384c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9pf-M8OliCMfsr4MSRJOIrJfgAnX0Ng',
    appId: '1:846756640287:ios:ad7f3b0998749ed0cf872a',
    messagingSenderId: '846756640287',
    projectId: 'evahak-6384c',
    storageBucket: 'evahak-6384c.appspot.com',
    iosBundleId: 'com.example.eVahak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9pf-M8OliCMfsr4MSRJOIrJfgAnX0Ng',
    appId: '1:846756640287:ios:8fcd95693355d271cf872a',
    messagingSenderId: '846756640287',
    projectId: 'evahak-6384c',
    storageBucket: 'evahak-6384c.appspot.com',
    iosBundleId: 'com.example.eVahak.RunnerTests',
  );
}
